server:
  port: 8088

---

spring:
  profiles: default
  cloud:
    gateway:
#<<< API Gateway / Routes
      routes:
        - id: monitoring
          uri: http://localhost:8082
          predicates:
            - Path=, /phoneinfos/**
        - id: report
          uri: http://localhost:8083
          predicates:
            - Path=/reports/**, 
        - id: phonemanagement
          uri: http://localhost:8084
          predicates:
            - Path=/phonemanagements/**, 
        - id: alarm
          uri: http://localhost:8085
          predicates:
            - Path=/alarms/**, 
        - id: frontend
          uri: http://localhost:8080
          predicates:
            - Path=/**
#>>> API Gateway / Routes
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true


---

spring:
  profiles: docker
  cloud:
    gateway:
      routes:
        - id: monitoring
          uri: http://monitoring:8080
          predicates:
            - Path=, 
        - id: report
          uri: http://report:8080
          predicates:
            - Path=/reports/**, 
        - id: phonemanagement
          uri: http://phonemanagement:8080
          predicates:
            - Path=/phonemanagements/**, 
        - id: alarm
          uri: http://alarm:8080
          predicates:
            - Path=/alarms/**, 
        - id: frontend
          uri: http://frontend:8080
          predicates:
            - Path=/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true

server:
  port: 8080
